repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: frontend-lint
        name: Frontend Lint
        entry: bash -c 'cd frontend && npm run lint'
        language: system
        files: ^frontend/
        pass_filenames: false

      - id: backend-lint
        name: Backend Lint
        entry: bash -c 'cd backend && poetry run ruff check .'
        language: system
        files: ^backend/
        pass_filenames: false

      - id: backend-test
        name: Backend Test
        entry: bash -c 'cd backend && poetry run pytest'
        language: system
        files: ^backend/
        pass_filenames: false

      - id: backend-coverage
        name: Backend Coverage
        entry: bash -c 'cd backend && poetry run coverage erase && poetry run coverage run -m pytest && poetry run coverage report -m && poetry run coverage xml'
        language: system
        files: ^backend/
        pass_filenames: false
